const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let me=null,contacts=[],groups=[],conversations=[],selected=null,filter='all',socket=null,typingTimer=null,peer=null,localStream=null,currentCall=null,iceQueue=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=n=>String(n||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt,headers:{...(opt.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(r.status===401){location.href='index.html';throw Error('Session expired')}if(!r.ok)throw Error(d.error||'Request failed');return d}
function avatar(u){return `<div class="avatar">${esc(u.avatar||initials(u.name))}</div>`}
function time(v){return new Date(v).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}
async function boot(){try{const m=await api('/api/auth/me');me=m.user;$('#myName').textContent=me.name;$('#myAvatar').textContent=me.avatar||initials(me.name);const c=await api('/api/contacts');contacts=c.contacts;groups=c.groups;await loadConversations();connectSocket();renderList()}catch(e){console.error(e)}}
async function loadConversations(){const d=await api('/api/conversations');conversations=d.conversations.map(c=>{if(c.type==='direct'){const u=c.user;return {id:c.id,type:'direct',name:u.name,avatar:u.avatar,online:u.status==='online',userId:u.id,preview:c.lastMessage?.text||'Start a conversation',time:c.lastMessage?.createdAt||null,unread:0}}const g=groups.find(x=>x.id===c.id)||c;return {id:c.id,type:'group',name:g.name,avatar:g.avatar,members:g.members?.length||0,preview:c.lastMessage?.text||'No messages yet',time:c.lastMessage?.createdAt||null,unread:0}})}
function renderList(){const q=$('#chatSearch').value.trim().toLowerCase();let list=conversations.filter(c=>(filter==='all'||(filter==='groups'&&c.type==='group')||(filter==='online'&&c.online)||(filter==='unread'&&c.unread>0))&&c.name.toLowerCase().includes(q));list.sort((a,b)=>(new Date(b.time||0)-new Date(a.time||0)));$('#chatList').innerHTML=list.map(c=>`<article class="chat-item ${selected?.id===c.id?'active':''}" data-id="${esc(c.id)}"><div class="avatar-wrap">${avatar(c)}${c.online?'<i class="presence"></i>':''}</div><div class="chat-copy"><div class="chat-name"><strong>${esc(c.name)}</strong><time>${c.time?esc(time(c.time)):''}</time></div><p>${esc(c.preview||'')}</p></div>${c.unread?`<b class="unread-badge">${c.unread>9?'9+':c.unread}</b>`:''}</article>`).join('')||'<div class="empty-list">No conversations found.</div>';$$('.chat-item').forEach(x=>x.onclick=()=>selectChat(x.dataset.id))}
async function selectChat(id){selected=conversations.find(c=>c.id===id);if(!selected)return;$('#chatName').textContent=selected.name;$('#chatAvatar').textContent=selected.avatar||initials(selected.name);$('#chatStatus').textContent=selected.type==='group'?`${selected.members} members • Group chat`:(selected.online?'Online now':'Offline');$('#messageInput').disabled=false;$('#messageInput').placeholder=`Message ${selected.name}`;$('.send-btn').disabled=false;if(socket)socket.emit('conversation:join',selected.id);await renderConversation();renderList();closeSidebar()}
async function renderConversation(){if(!selected)return;const d=await api('/api/messages/'+encodeURIComponent(selected.id));const html=d.messages.map(m=>{const mine=m.senderId===me.id;const attachment=m.attachment?`<a class="attachment" href="${esc(m.attachment.url)}" target="_blank">📎 ${esc(m.attachment.name)}</a>`:'';return `<div class="message-row ${mine?'me':''}">${!mine?avatar(m.sender):''}<div class="message-bundle"><div class="message">${esc(m.text||'')}${attachment}</div><div class="message-meta"><span>${selected.type==='group'&&!mine?esc(m.sender.name):mine?'You':''}</span><span>${esc(time(m.createdAt))}</span><span>${mine?'✓✓':''}</span></div></div></div>`}).join('');$('#conversation').innerHTML=html||`<div class="welcome-state"><div class="welcome-orb">💬</div><h1>Start the conversation.</h1><p>Send the first message to ${esc(selected.name)}.</p></div>`;requestAnimationFrame(()=>$('#conversation').scrollTop=$('#conversation').scrollHeight)}
function connectSocket(){socket=io({withCredentials:true});socket.on('connect_error',()=>showToast('Live connection unavailable'));socket.on('message:new',m=>{const c=conversations.find(x=>x.id===m.conversationId);if(!c)return;c.preview=m.text||'Attachment';c.time=m.createdAt;if(selected?.id===c.id)renderConversation();else c.unread=(c.unread||0)+1;renderList()});socket.on('presence:update',p=>{const c=conversations.find(x=>x.userId===p.userId);if(c){c.online=p.status==='online';if(selected?.id===c.id)$('#chatStatus').textContent=c.online?'Online now':'Offline';renderList()}});socket.on('typing',p=>{if(selected?.id===p.conversationId&&p.user?.id!==me.id)$('#typing').classList.toggle('show',p.active)});socket.on('call:offer',handleOffer);socket.on('call:answer',async p=>{if(peer)await peer.setRemoteDescription(new RTCSessionDescription(p.answer))});socket.on('call:ice',async p=>{try{if(p.candidate){if(peer&&peer.remoteDescription)await peer.addIceCandidate(new RTCIceCandidate(p.candidate));else iceQueue.push(p.candidate)}}catch{}});socket.on('call:end',endCall)}
$('#messageForm').onsubmit=async e=>{e.preventDefault();if(!selected)return;const input=$('#messageInput'),text=input.value.trim();if(!text)return;try{await api('/api/messages',{method:'POST',body:JSON.stringify({conversationId:selected.id,text})});input.value='';autoSize();socket?.emit('typing:stop',selected.id)}catch(e){showToast(e.message)}};
$('#messageInput').oninput=()=>{autoSize();if(!selected||!socket)return;socket.emit('typing:start',selected.id);clearTimeout(typingTimer);typingTimer=setTimeout(()=>socket.emit('typing:stop',selected.id),700)};$('#messageInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#messageForm').requestSubmit()}};
function autoSize(){const t=$('#messageInput');t.style.height='auto';t.style.height=Math.min(t.scrollHeight,110)+'px'}
async function newChat(){showModal(`<div class="modal-head"><div><span class="eyebrow">DISCOVER PEOPLE</span><h2>Start a conversation</h2></div><button class="modal-close">×</button></div><div class="discover-search"><input id="peopleSearch" placeholder="Search registered users…"></div><div class="people-results" id="peopleResults">Loading…</div><hr><div class="modal-head"><div><span class="eyebrow">COMMUNITY</span><h2>Create a group</h2></div></div><input id="groupName" class="modal-input" placeholder="Group name"><button class="modal-btn primary" id="createGroup">Create group</button>`);const renderPeople=async()=>{const q=$('#peopleSearch').value.trim();const d=await api('/api/users?q='+encodeURIComponent(q));$('#peopleResults').innerHTML=d.users.map(u=>`<button class="person-row" data-user="${u.id}">${avatar(u)}<span><strong>${esc(u.name)}</strong><small>${esc(u.email)}</small></span></button>`).join('')||'<p class="muted">No users found.</p>';$$('[data-user]').forEach(b=>b.onclick=async()=>{const x=await api('/api/conversations/direct',{method:'POST',body:JSON.stringify({userId:b.dataset.user})});closeModal();await loadConversations();await selectChat(x.conversation.id)})};$('#peopleSearch').oninput=renderPeople;await renderPeople();$('#createGroup').onclick=async()=>{const name=$('#groupName').value.trim();if(!name)return showToast('Enter a group name');const d=await api('/api/groups',{method:'POST',body:JSON.stringify({name,memberIds:[]})});closeModal();await loadConversations();await selectChat(d.group.id)}}
async function attach(){const input=document.createElement('input');input.type='file';input.accept='image/*,video/*,audio/*,.pdf,.txt';input.onchange=async()=>{if(!input.files[0]||!selected)return;const fd=new FormData();fd.append('file',input.files[0]);try{const d=await api('/api/upload',{method:'POST',body:fd});await api('/api/messages',{method:'POST',body:JSON.stringify({conversationId:selected.id,attachment:d.attachment,text:''})});await renderConversation()}catch(e){showToast(e.message)}};input.click()}
$('#attachBtn').onclick=attach;$('#emojiBtn').onclick=()=>{$('#messageInput').value+=' 😊';$('#messageInput').focus();autoSize()};let rec=null,parts=[];$('#voiceBtn').onclick=async()=>{if(rec?.state==='recording'){rec.stop();return}try{const s=await navigator.mediaDevices.getUserMedia({audio:true});rec=new MediaRecorder(s);parts=[];rec.ondataavailable=e=>parts.push(e.data);rec.onstop=()=>{s.getTracks().forEach(t=>t.stop());showToast('Voice note recorded locally. Add storage upload to persist audio.');rec=null};rec.start();$('#voiceBtn').textContent='⏹'}catch{showToast('Microphone permission was denied')}};
function showModal(html){$('#modalContent').innerHTML=html;$('#modalLayer').classList.add('show');$$('.modal-close').forEach(b=>b.onclick=closeModal)}function closeModal(){$('#modalLayer').classList.remove('show');$('#modalContent').innerHTML=''}$('#modalLayer').onclick=e=>{if(e.target.id==='modalLayer')closeModal()};
function profile(){showModal(`<div class="modal-head"><div><span class="eyebrow">YOUR PROFILE</span><h2>${esc(me.name)}</h2></div><button class="modal-close">×</button></div><div class="profile-big">${avatar({...me,avatar:me.avatar||initials(me.name)})}<div><strong>${esc(me.name)}</strong><p>${esc(me.email)}</p></div></div><div class="setting-item"><span>Member since</span><strong>${new Date(me.createdAt).toLocaleDateString()}</strong></div><div class="setting-item"><span>Status</span><strong>● Active now</strong></div>`)}
function settings(){showModal(`<div class="modal-head"><div><span class="eyebrow">CONTROL CENTER</span><h2>Settings</h2></div><button class="modal-close">×</button></div><div class="setting-item"><span>Account</span><strong>${esc(me.email)}</strong></div><div class="setting-item"><span>Theme</span><strong>Midnight Luxury</strong></div><div class="setting-item"><span>Real-time</span><strong>Socket.IO enabled</strong></div><div class="setting-item"><span>Calls</span><strong>WebRTC enabled</strong></div><button class="modal-btn danger" id="modalLogout">Log out</button>`);$('#modalLogout').onclick=logout}
async function logout(){try{await api('/api/auth/logout',{method:'POST'})}finally{location.href='index.html'}}
function showToast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>$('#toast').classList.remove('show'),2400)}
$('#settingsBtn').onclick=settings;$('#settingsBtn2').onclick=settings;$('#profileBtn').onclick=profile;$('#mobileProfile').onclick=profile;$('#mobileSettings').onclick=settings;$('#newChatBtn').onclick=newChat;$('#welcomeNewChat').onclick=newChat;$('#logoutBtn').onclick=logout;$('#chatSearch').oninput=renderList;$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderList()});
function openSidebar(){$('#sidebar').classList.add('open');$('#backdrop').classList.add('show')}function closeSidebar(){$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('show')}$('#openSidebar').onclick=openSidebar;$('#closeSidebar').onclick=closeSidebar;$('#backdrop').onclick=closeSidebar;$('#mobileChats').onclick=closeSidebar;$('#mobilePeople').onclick=newChat;

async function makePeer(targetId,isCaller,video){peer=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]});peer.onicecandidate=e=>e.candidate&&socket.emit('call:ice',{to:targetId,candidate:e.candidate});peer.ontrack=e=>{const v=$('#remoteVideo');if(v)v.srcObject=e.streams[0]};if(!localStream)localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:video});localStream.getTracks().forEach(t=>peer.addTrack(t,localStream));const lv=$('#localVideo');if(lv)lv.srcObject=localStream;if(iceQueue.length&&peer.remoteDescription){for(const c of iceQueue.splice(0))await peer.addIceCandidate(new RTCIceCandidate(c))}if(isCaller){const offer=await peer.createOffer();await peer.setLocalDescription(offer);socket.emit('call:offer',{to:targetId,offer:{type:offer.type,sdp:offer.sdp},video})}}
async function startCall(type){if(!selected||selected.type!=='direct')return showToast('Calls are available for direct contacts.');if(selected.online!==true)return showToast('This contact is offline.');const video=type==='video';currentCall={targetId:selected.userId,video};showCallModal(video,selected.name,'Calling…');try{await makePeer(selected.userId,true,video)}catch(e){showToast('Camera/microphone permission is required.');endCall()}}
async function handleOffer(p){if(!p?.from)return;currentCall={targetId:p.from,video:!!p.video};showCallModal(!!p.video,p.fromUser?.name||'Incoming call','Incoming call');const accept=$('#acceptCall');if(accept)accept.onclick=async()=>{accept.remove();try{await makePeer(p.from,false,!!p.video);await peer.setRemoteDescription(new RTCSessionDescription(p.offer));const ans=await peer.createAnswer();await peer.setLocalDescription(ans);if(iceQueue.length&&peer.remoteDescription){for(const c of iceQueue.splice(0))await peer.addIceCandidate(new RTCIceCandidate(c))}socket.emit('call:answer',{to:p.from,answer:{type:ans.type,sdp:ans.sdp}});$('#callState').textContent='Connected'}catch{showToast('Unable to access camera/microphone');endCall()}}}
function showCallModal(video,name,state){showModal(`<div class="call-modal"><div class="call-head"><div><span class="eyebrow">${video?'VIDEO':'AUDIO'} CALL</span><h2>${esc(name)}</h2><p id="callState">${esc(state)}</p></div><button class="modal-close">×</button></div>${video?'<div class="video-stage"><video id="remoteVideo" autoplay playsinline></video><video id="localVideo" autoplay muted playsinline></video></div>':'<div class="call-orb">☎</div>'}<div class="call-controls">${state==='Incoming call'?'<button id="acceptCall" class="accept">✓</button>':''}<button id="muteCall">🎙</button><button id="endCall" class="end">✕</button><button id="cameraToggle">▣</button></div></div>`);$('#endCall').onclick=endCall;$$('.modal-close').forEach(b=>b.onclick=endCall);$('#muteCall').onclick=()=>{if(localStream)localStream.getAudioTracks().forEach(t=>t.enabled=!t.enabled)};$('#cameraToggle').onclick=()=>{if(localStream)localStream.getVideoTracks().forEach(t=>t.enabled=!t.enabled)}}
function endCall(){if(currentCall&&socket)socket.emit('call:end',{to:currentCall.targetId});if(peer){peer.close();peer=null}if(localStream){localStream.getTracks().forEach(t=>t.stop());localStream=null}currentCall=null;iceQueue=[];closeModal()}
$('#audioCall').onclick=()=>startCall('audio');$('#videoCall').onclick=()=>startCall('video');$('#searchMessages').onclick=()=>showToast('Use the chat search box to find people.');$('#moreBtn').onclick=settings;
boot();
